function [tm_cell,um_cell,tcellpopm_cell,cellpopm_cell,surv_curvm_MGMT_M,surv_curvm_MGMT_P]=Calib_TMZ_PK_PD_V28_2ndstep_p53_IC50_0(TMZout0_surv,inhib_factor,DMSO_pop_MGMT_M,DMSO_pop_MGMT_P)


%% Fix simulation index
sim_indx(TMZout0_surv)

%% volume in L
Vcell=7*1e-12;
%intracellular volume in L
Vin=1e6*Vcell;
%extracellular medium in L
Vout=2e-3;

%% Time in hours
[numb_comptime1,t_surv] = simulations_time();

%% Initial conditions, in microM
[TMZin0,MTICout0,MTICin0,AICout0,AICin0,Cat0,mO60,RNA_MGMT0,MGMT0_U87_LN229,GT0,SSB0,Cdc250,RNA_Mdm20,Mdm20,cell_pop0,cell_pop_norm0_Jack_MGMT_M] = def_int_cond();

%% PARAMETERS 
[pT,pA,pT2,pA2,kT0,lambdaT,kM0,lambdaM,pH0,kcat,dna,kt_MGMT,kd_MGMT,omega_cc,t0_cc,M_cc,A_cc,phi_cc,n_cc,...
    k_GT,k_MMR,k_BER,k_HR,kf_ATR_MGMT_M,kd_ATR,n_add,kf_Chk1_MGMT_M,kd_Chk1,kd_cdc25,n_cdc25,...
    n_ATR,kd_p53,kd_p53Mdm2,n_Mdm2,K_Mdm2,kt_Mdm2,kt_Mdm2p53,n_p53,kf_Mdm2,n_p53int] = def_params();

%% PARAMETERS to estimate
[MGMT_P0,k_MGMT,k_addO,k_addN,DSB_72h_fac,k_DSBO,k_DSBN,k_CyA,kf_ATR_MGMT_P,k_ATR,K_add,kd_pATR,k_Chk1,C_Chk1,kd_pChk1,k_cdc25,K_cdc25,...
kf_p53,k_p53,K_ATR,kp_ser46,K_p53,upAsy,sness,k_apop,tED50,cell_pop_norm0_Jack_MGMT_P...
] = def_params_toEstimate();

%% Elements depending on PARAMETERS
[ktd_MGMT,kf_MGMT_M,kf_MGMT_P,K_cc,k_addEx,mN370,DSB0,...
    ATR0_MGMT_M,pATR0_MGMT_M,...
    ATR0_MGMT_P,pATR0_MGMT_P,...
    Chk10_MGMT_M,kf_Chk1_MGMT_P,Chk10_MGMT_P,...
    pChk10_MGMT_M,pChk10_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    p530_MGMT_M,p530_MGMT_P,p53_ser460_MGMT_M,p53_ser460_MGMT_P,kd_ser46_MGMT_M,kd_ser46_MGMT_P,ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P,kd_Mdm2] = param_dep_elem(...
    kt_MGMT,RNA_MGMT0,MGMT0_U87_LN229,MGMT_P0,kd_MGMT,...
    Cdc250,t0_cc,M_cc,A_cc,omega_cc,phi_cc,K_cdc25,n_cdc25,...
    DSB_72h_fac,k_HR,k_DSBN,k_CyA,n_cc,...
    k_BER,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,k_ATR,n_add,K_add,kd_ATR,...
    kd_pATR,...
    kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,C_Chk1,...
    kd_pChk1,...
    k_cdc25,kd_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,Mdm20,n_Mdm2,K_Mdm2,kp_ser46,...
    kt_Mdm2,kt_Mdm2p53,n_p53,K_p53,RNA_Mdm20,kf_Mdm2);

%% Inhibition
[k_addO,RNA_MGMT0,MGMT0_U87_LN229,MGMT_P0,kt_MGMT,ktd_MGMT,kf_MGMT_M,kf_MGMT_P,k_MGMT,kd_MGMT,k_GT,k_MMR,...
    k_addN,k_addEx,mN370,k_BER,k_DSBO,k_DSBN,DSB0,k_HR,ATR0_MGMT_M,ATR0_MGMT_P,pATR0_MGMT_M,pATR0_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,k_ATR,kd_ATR,kd_pATR,Chk10_MGMT_M,Chk10_MGMT_P,pChk10_MGMT_M,pChk10_MGMT_P,kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,kd_Chk1,k_Chk1,kd_pChk1,...
    Cdc250,kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,k_CyA,p530_MGMT_M,p530_MGMT_P,p53_ser460_MGMT_M,p53_ser460_MGMT_P,kf_p53,...
    k_p53,kd_p53,kd_p53Mdm2,kp_ser46,kd_ser46_MGMT_M,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,RNA_Mdm20,Mdm20,ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2] = inhibition_func(inhib_factor,...
    k_addO,RNA_MGMT0,MGMT0_U87_LN229,MGMT_P0,kt_MGMT,ktd_MGMT,kf_MGMT_M,kf_MGMT_P,k_MGMT,kd_MGMT,k_GT,k_MMR,...
    k_addN,k_addEx,mN370,k_BER,k_DSBO,k_DSBN,DSB0,k_HR,ATR0_MGMT_M,ATR0_MGMT_P,pATR0_MGMT_M,pATR0_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,k_ATR,kd_ATR,kd_pATR,Chk10_MGMT_M,Chk10_MGMT_P,pChk10_MGMT_M,pChk10_MGMT_P,kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,kd_Chk1,k_Chk1,kd_pChk1,...
    Cdc250,kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,k_CyA,p530_MGMT_M,p530_MGMT_P,p53_ser460_MGMT_M,p53_ser460_MGMT_P,kf_p53,...
    k_p53,kd_p53,kd_p53Mdm2,kp_ser46,kd_ser46_MGMT_M,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,RNA_Mdm20,Mdm20,ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);

%% Simulation Initial conditions
[int_cond_mat]= initial_cond_func(TMZout0_surv,...
    TMZin0,MTICout0,MTICin0,AICout0,AICin0,Cat0,...
    mO60,RNA_MGMT0,GT0,SSB0,mN370,DSB0,Cdc250,RNA_Mdm20,Mdm20,...
    MGMT0_U87_LN229,MGMT_P0,...
    ATR0_MGMT_M,ATR0_MGMT_P,...
    pATR0_MGMT_M,pATR0_MGMT_P,...
    Chk10_MGMT_M,Chk10_MGMT_P,...
    pChk10_MGMT_M,pChk10_MGMT_P,...
    p530_MGMT_M,p530_MGMT_P,...
    p53_ser460_MGMT_M,p53_ser460_MGMT_P);

%% PK-PD Model
[tm_cell,um_cell] = simulations_PKPD(t_surv,...
    int_cond_mat,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kt_MGMT,ktd_MGMT,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    k_Chk1,kd_Chk1,kd_pChk1,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,kf_Mdm2,kd_Mdm2,...
    kf_MGMT_M,kf_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,...
    kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    kd_ser46_MGMT_M,kd_ser46_MGMT_P,...
    ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P...
    );

%% Cell population 
[surv_curvm_MGMT_M,surv_curvm_MGMT_P,...
    tcellpopm_cell,cellpopm_cell]=simulations_surv_curv(tm_cell,um_cell,cell_pop0,k_apop,n_p53int,upAsy,sness,tED50,...
    TMZout0_surv,...
    numb_comptime1,...
    cell_pop_norm0_Jack_MGMT_M,cell_pop_norm0_Jack_MGMT_P,...
    DMSO_pop_MGMT_M,DMSO_pop_MGMT_P);

end
