function [tm_cell,um_cell] = simulations_PKPD(t_surv,...
    int_cond_mat,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kt_MGMT,ktd_MGMT,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    k_Chk1,kd_Chk1,kd_pChk1,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,kf_Mdm2,kd_Mdm2,...
    kf_MGMT_M,kf_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,...
    kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    kd_ser46_MGMT_M,kd_ser46_MGMT_P,...
    ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P...
    )

global sn_MGMT_M_vec sn_MGMT_P_vec...
       sim_num

tm_cell=cell(1,sim_num);
um_cell=cell(1,sim_num);
%solver-> ode#15s ode#23tb
%% Simulations cell TMZ survival
%  MGMT-
for index=1:length(sn_MGMT_M_vec)
    [tm_cell{sn_MGMT_M_vec(index)},um_cell{sn_MGMT_M_vec(index)}]=ode23tb(@TMZ_PK_PD_ODE,t_surv,int_cond_mat(:,sn_MGMT_M_vec(index)),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kt_MGMT,ktd_MGMT,kf_MGMT_M,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

% MGMT+
for index=1:length(sn_MGMT_P_vec)
    [tm_cell{sn_MGMT_P_vec(index)},um_cell{sn_MGMT_P_vec(index)}]=ode23tb(@TMZ_PK_PD_ODE,t_surv,int_cond_mat(:,sn_MGMT_P_vec(index)),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kt_MGMT,ktd_MGMT,kf_MGMT_P,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

end

