function MAIN_vitural_pop_read ()

% The following code has for goal to read the results of the simulations
% generated with "vitural_pop_creation.m" and colleted in the folder
% "Results"

clear all
format long
%% Computational Time Start
now1 = tic();

%% Set paths
my_dir = fileparts(which(mfilename));

% Set current directory to 'my_dir' and add path to sub-folders:
restoredefaultpath
cd(my_dir)
% addpath(genpath(my_dir))
addpath(genpath('./cellpop_module'))
addpath(genpath('./fig_funcs'))
addpath(genpath('./Legend_colors'))

%% Create Results folder
% Results_dir=mkdir_results();

%% Plot control
[plot_surv_TMZalone_figcon,plot_surv_BERinh_figcon,plot_surv_HRinh_figcon,plot_surv_HRBERinh_figcon,...
    hist_survcurv_AUC_MGMT_M_TMZalone_figcon,hist_survcurv_AUC_MGMT_P_TMZalone_figcon,hist_survcurv_AUC_allpat_TMZalone_figcon,...
    hist_survcurv_AUC_treat_BERinh_figcon,hist_survcurv_AUC_treat_HRinh_figcon,hist_survcurv_AUC_treat_HRBERinh_figcon,...
    hist_survcurv_AUC_2treat_BERinh_figcon,hist_survcurv_AUC_2treat_HRinh_figcon,hist_survcurv_AUC_2treat_HRBERinh_figcon,...
    plot_surv_TMZalone_fignumb,plot_surv_BERinh_fignumb,plot_surv_HRinh_fignumb,plot_surv_HRBERinh_fignumb,...
    hist_survcurv_AUC_MGMT_M_TMZalone_fignumb,hist_survcurv_AUC_MGMT_P_TMZalone_fignumb,hist_survcurv_AUC_allpat_TMZalone_fignumb,...
    hist_survcurv_AUC_treat_BERinh_fignumb,hist_survcurv_AUC_treat_HRinh_fignumb,hist_survcurv_AUC_treat_HRBERinh_fignumb,...
    hist_survcurv_AUC_2treat_BERinh_fignumb,hist_survcurv_AUC_2treat_HRinh_fignumb,hist_survcurv_AUC_2treat_HRBERinh_fignumb...
    ] = plot_control();

%% Read virtual population
Results_data_dir_TMZalone='Results_2024-03-29_15.30.14_TMZalone';
Results_data_dir_BERinh='Results_2024-03-30_19.53.04_BERinh';
Results_data_dir_HRinh='Results_2024-03-31_07.08.57_HRinh';
Results_data_dir_HRBERinh='Results_2024-03-29_21.48.48_HRBERinh';


[dataset_MGMT_M_TMZalone,dataset_MGMT_P_TMZalone,...
    surv_curvm_orig_MGMT_M_TMZalone,surv_curvm_orig_MGMT_P_TMZalone,surv_curvm_mat_MGMT_M_TMZalone,surv_curvm_mat_MGMT_P_TMZalone,...
    survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,...
    survcurv_AUC_vec_allpat_TMZalone] = read_populatio_dataset(Results_data_dir_TMZalone);

[dataset_MGMT_M_BERinh,dataset_MGMT_P_BERinh,...
    surv_curvm_orig_MGMT_M_BERinh,surv_curvm_orig_MGMT_P_BERinh,surv_curvm_mat_MGMT_M_BERinh,surv_curvm_mat_MGMT_P_BERinh,...
    survcurv_AUC_orig_MGMT_M_BERinh,survcurv_AUC_orig_MGMT_P_BERinh,survcurv_AUC_vec_MGMT_M_BERinh,survcurv_AUC_vec_MGMT_P_BERinh,...
    survcurv_AUC_vec_allpat_BERinh] = read_populatio_dataset(Results_data_dir_BERinh);

[dataset_MGMT_M_HRinh,dataset_MGMT_P_HRinh,...
    surv_curvm_orig_MGMT_M_HRinh,surv_curvm_orig_MGMT_P_HRinh,surv_curvm_mat_MGMT_M_HRinh,surv_curvm_mat_MGMT_P_HRinh,...
    survcurv_AUC_orig_MGMT_M_HRinh,survcurv_AUC_orig_MGMT_P_HRinh,survcurv_AUC_vec_MGMT_M_HRinh,survcurv_AUC_vec_MGMT_P_HRinh,...
    survcurv_AUC_vec_allpat_HRinh] = read_populatio_dataset(Results_data_dir_HRinh);

[dataset_MGMT_M_HRBERinh,dataset_MGMT_P_HRBERinh,...
    surv_curvm_orig_MGMT_M_HRBERinh,surv_curvm_orig_MGMT_P_HRBERinh,surv_curvm_mat_MGMT_M_HRBERinh,surv_curvm_mat_MGMT_P_HRBERinh,...
    survcurv_AUC_orig_MGMT_M_HRBERinh,survcurv_AUC_orig_MGMT_P_HRBERinh,survcurv_AUC_vec_MGMT_M_HRBERinh,survcurv_AUC_vec_MGMT_P_HRBERinh,...
    survcurv_AUC_vec_allpat_HRBERinh] = read_populatio_dataset(Results_data_dir_HRBERinh);
TMZout0_surv=[0 1 2 4 8 16 32 64 128 256 512 1024 3e3]';

%% Plot virtual population
patient_num_plot_surv_curv=200;
plot_setting_viab_control(TMZout0_surv,surv_curvm_orig_MGMT_M_TMZalone,surv_curvm_orig_MGMT_P_TMZalone,...
    patient_num_plot_surv_curv,surv_curvm_mat_MGMT_M_TMZalone,surv_curvm_mat_MGMT_P_TMZalone,...
    plot_surv_TMZalone_figcon,plot_surv_TMZalone_fignumb)

plot_setting_viab_control(TMZout0_surv,surv_curvm_orig_MGMT_M_BERinh,surv_curvm_orig_MGMT_P_BERinh,...
    patient_num_plot_surv_curv,surv_curvm_mat_MGMT_M_BERinh,surv_curvm_mat_MGMT_P_BERinh,...
    plot_surv_BERinh_figcon,plot_surv_BERinh_fignumb)

plot_setting_viab_control(TMZout0_surv,surv_curvm_orig_MGMT_M_HRinh,surv_curvm_orig_MGMT_P_HRinh,...
    patient_num_plot_surv_curv,surv_curvm_mat_MGMT_M_HRinh,surv_curvm_mat_MGMT_P_HRinh,...
    plot_surv_HRinh_figcon,plot_surv_HRinh_fignumb)

plot_setting_viab_control(TMZout0_surv,surv_curvm_orig_MGMT_M_HRBERinh,surv_curvm_orig_MGMT_P_HRBERinh,...
    patient_num_plot_surv_curv,surv_curvm_mat_MGMT_M_HRBERinh,surv_curvm_mat_MGMT_P_HRBERinh,...
    plot_surv_HRBERinh_figcon,plot_surv_HRBERinh_fignumb)

%% Plot AUC virtual population histogram
%TMZ alone
plot_AUCHist(survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_M_TMZalone,'m','A',hist_survcurv_AUC_MGMT_M_TMZalone_figcon,hist_survcurv_AUC_MGMT_M_TMZalone_fignumb,'TMZ alone')
plot_AUCHist(survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,'p','A',hist_survcurv_AUC_MGMT_P_TMZalone_figcon,hist_survcurv_AUC_MGMT_P_TMZalone_fignumb,'TMZ alone')
plot_AUCHist(survcurv_AUC_vec_allpat_TMZalone,survcurv_AUC_orig_MGMT_M_TMZalone,'a','A',hist_survcurv_AUC_allpat_TMZalone_figcon,hist_survcurv_AUC_allpat_TMZalone_fignumb,'TMZ alone')

%Treatments
plot_AUCHist_treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_BERinh,survcurv_AUC_vec_MGMT_P_BERinh,survcurv_AUC_vec_allpat_BERinh,...
    hist_survcurv_AUC_treat_BERinh_figcon,hist_survcurv_AUC_treat_BERinh_fignumb,'BER inh.')
plot_AUCHist_treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_HRinh,survcurv_AUC_vec_MGMT_P_HRinh,survcurv_AUC_vec_allpat_HRinh,...
    hist_survcurv_AUC_treat_HRinh_figcon,hist_survcurv_AUC_treat_HRinh_fignumb,'HR inh.')
plot_AUCHist_treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_HRBERinh,survcurv_AUC_vec_MGMT_P_HRBERinh,survcurv_AUC_vec_allpat_HRBERinh,...
    hist_survcurv_AUC_treat_HRBERinh_figcon,hist_survcurv_AUC_treat_HRBERinh_fignumb,'HR&BER inh.')

%TMZ alone and Treatments
plot_AUCHist_2treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_BERinh,survcurv_AUC_vec_MGMT_P_BERinh,survcurv_AUC_vec_allpat_BERinh,...
    1,hist_survcurv_AUC_2treat_BERinh_figcon,hist_survcurv_AUC_2treat_BERinh_fignumb)

plot_AUCHist_2treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_HRinh,survcurv_AUC_vec_MGMT_P_HRinh,survcurv_AUC_vec_allpat_HRinh,...
    2,hist_survcurv_AUC_2treat_HRinh_figcon,hist_survcurv_AUC_2treat_HRinh_fignumb)

plot_AUCHist_2treat_settings(survcurv_AUC_orig_MGMT_M_TMZalone,survcurv_AUC_orig_MGMT_P_TMZalone,...
    survcurv_AUC_vec_MGMT_M_TMZalone,survcurv_AUC_vec_MGMT_P_TMZalone,survcurv_AUC_vec_allpat_TMZalone,...
    survcurv_AUC_vec_MGMT_M_HRBERinh,survcurv_AUC_vec_MGMT_P_HRBERinh,survcurv_AUC_vec_allpat_HRBERinh,...
    3,hist_survcurv_AUC_2treat_HRBERinh_figcon,hist_survcurv_AUC_2treat_HRBERinh_fignumb)


%% Computational Time End
wholeTime = toc(now1)
disp('sec')


end


