   function [] = plot_paper_tempDyn_TMZVX_data(fig_num,data_mat,MGMT,TMZ,TMZout0_MAX,VX,gen_subplot_vec)

dataset_num=size(data_mat,2)/2;
color_mat = color_TMZVXdef(dataset_num,MGMT,TMZ,TMZout0_MAX,VX);

    figure(fig_num)
    for n=1:dataset_num
        subplot(2,3,gen_subplot_vec(n))
        hold on
        scatter(data_mat(:,2*n-1),1e3*data_mat(:,2*n),80,'filled','MarkerFaceColor',color_mat(n,1:3),'MarkerEdgeColor',[0 0 0],'MarkerFaceAlpha',color_mat(n,4))
        box off
    end


    figure(fig_num)
    subplot(2,3,2)
    legend({'MGMT-,TMZ=0nM,VX=0nM',...
        'MGMT-,TMZ=100nM,VX=0nM',...
        'MGMT-,TMZ=100nM,VX=8nM',...
        'MGMT-,TMZ=100nM,VX=40nM',...
        'MGMT-,TMZ=100nM,VX=200nM',...
        'MGMT-,TMZ=100nM,VX=1000nM',...
        'MGMT+,TMZ=0nM,VX=0nM',...
        'MGMT+,TMZ=100nM,VX=0nM',...
        'MGMT+,TMZ=100nM,VX=8nM',...
        'MGMT+,TMZ=100nM,VX=40nM',...
        'MGMT+,TMZ=100nM,VX=200nM',...
        'MGMT+,TMZ=100nM,VX=1000nM'},...
        'NumColumns',1,'fontweight','normal','FontSize',10,'Location','best')

end
