function plot_setting_PKPD(TMZout0_surv_Verre_MGMT_M,TMZout0_surv_Verre_MGMT_P,tm_cell,um_cell,CyAm_cell,...simulation
    Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZalone_PKPDplot_fignumb,...plot control
    Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZNip_PKPDplot_fignumb,...
    Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1_PKPDplot_fignumb,...
    Verre_surv_TMZRI1Nip_PKPDplot_fig,Verre_surv_TMZRI1Nip_PKPDplot_fignumb...
    )

global sn_Verre_TMZalone_0TMZ_MGMT_M sn_Verre_TMZalone_5TMZ_MGMT_M sn_Verre_TMZalone_25TMZ_MGMT_M sn_Verre_TMZalone_50TMZ_MGMT_M sn_Verre_TMZalone_100TMZ_MGMT_M sn_Verre_TMZalone_200TMZ_MGMT_M sn_Verre_TMZalone_400TMZ_MGMT_M sn_Verre_TMZalone_800TMZ_MGMT_M sn_Verre_TMZalone_1000TMZ_MGMT_M...
    sn_Verre_TMZalone_0TMZ_MGMT_P sn_Verre_TMZalone_5TMZ_MGMT_P sn_Verre_TMZalone_25TMZ_MGMT_P sn_Verre_TMZalone_50TMZ_MGMT_P sn_Verre_TMZalone_100TMZ_MGMT_P sn_Verre_TMZalone_200TMZ_MGMT_P sn_Verre_TMZalone_400TMZ_MGMT_P sn_Verre_TMZalone_800TMZ_MGMT_P sn_Verre_TMZalone_1000TMZ_MGMT_P...
    sn_Verre_TMZNip_0TMZ_MGMT_M sn_Verre_TMZNip_5TMZ_MGMT_M sn_Verre_TMZNip_25TMZ_MGMT_M sn_Verre_TMZNip_50TMZ_MGMT_M sn_Verre_TMZNip_100TMZ_MGMT_M sn_Verre_TMZNip_200TMZ_MGMT_M sn_Verre_TMZNip_400TMZ_MGMT_M sn_Verre_TMZNip_800TMZ_MGMT_M sn_Verre_TMZNip_1000TMZ_MGMT_M...
    sn_Verre_TMZNip_0TMZ_MGMT_P sn_Verre_TMZNip_5TMZ_MGMT_P sn_Verre_TMZNip_25TMZ_MGMT_P sn_Verre_TMZNip_50TMZ_MGMT_P sn_Verre_TMZNip_100TMZ_MGMT_P sn_Verre_TMZNip_200TMZ_MGMT_P sn_Verre_TMZNip_400TMZ_MGMT_P sn_Verre_TMZNip_800TMZ_MGMT_P sn_Verre_TMZNip_1000TMZ_MGMT_P...
    sn_Verre_TMZRI1_0TMZ_MGMT_M sn_Verre_TMZRI1_5TMZ_MGMT_M sn_Verre_TMZRI1_25TMZ_MGMT_M sn_Verre_TMZRI1_50TMZ_MGMT_M sn_Verre_TMZRI1_100TMZ_MGMT_M sn_Verre_TMZRI1_200TMZ_MGMT_M sn_Verre_TMZRI1_400TMZ_MGMT_M sn_Verre_TMZRI1_800TMZ_MGMT_M sn_Verre_TMZRI1_1000TMZ_MGMT_M...
    sn_Verre_TMZRI1_0TMZ_MGMT_P sn_Verre_TMZRI1_5TMZ_MGMT_P sn_Verre_TMZRI1_25TMZ_MGMT_P sn_Verre_TMZRI1_50TMZ_MGMT_P sn_Verre_TMZRI1_100TMZ_MGMT_P sn_Verre_TMZRI1_200TMZ_MGMT_P sn_Verre_TMZRI1_400TMZ_MGMT_P sn_Verre_TMZRI1_800TMZ_MGMT_P sn_Verre_TMZRI1_1000TMZ_MGMT_P...
    sn_Verre_TMZRI1Nip_0TMZ_MGMT_M sn_Verre_TMZRI1Nip_5TMZ_MGMT_M sn_Verre_TMZRI1Nip_25TMZ_MGMT_M sn_Verre_TMZRI1Nip_50TMZ_MGMT_M sn_Verre_TMZRI1Nip_100TMZ_MGMT_M sn_Verre_TMZRI1Nip_200TMZ_MGMT_M sn_Verre_TMZRI1Nip_400TMZ_MGMT_M sn_Verre_TMZRI1Nip_800TMZ_MGMT_M sn_Verre_TMZRI1Nip_1000TMZ_MGMT_M...
    sn_Verre_TMZRI1Nip_0TMZ_MGMT_P sn_Verre_TMZRI1Nip_5TMZ_MGMT_P sn_Verre_TMZRI1Nip_25TMZ_MGMT_P sn_Verre_TMZRI1Nip_50TMZ_MGMT_P sn_Verre_TMZRI1Nip_100TMZ_MGMT_P sn_Verre_TMZRI1Nip_200TMZ_MGMT_P sn_Verre_TMZRI1Nip_400TMZ_MGMT_P sn_Verre_TMZRI1Nip_800TMZ_MGMT_P sn_Verre_TMZRI1Nip_1000TMZ_MGMT_P...
    sim_number

%% Maité Verreault Simulations cell TMZ survival (TMZ alone)
Verre_surv_TMZalone_MGMT_M_t_cell={tm_cell{sn_Verre_TMZalone_0TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_5TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_25TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_50TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_100TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_200TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_400TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_800TMZ_MGMT_M} tm_cell{sn_Verre_TMZalone_1000TMZ_MGMT_M} };
Verre_surv_TMZalone_MGMT_M_sim_cell={um_cell{sn_Verre_TMZalone_0TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_5TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_25TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_50TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_100TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_200TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_400TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_800TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_1000TMZ_MGMT_M}};
Verre_surv_TMZalone_MGMT_M_CyA_cell={CyAm_cell{sn_Verre_TMZalone_0TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_5TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_25TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_50TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_100TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_200TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_400TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_800TMZ_MGMT_M} um_cell{sn_Verre_TMZalone_1000TMZ_MGMT_M}};

Verre_surv_TMZalone_MGMT_P_t_cell={tm_cell{sn_Verre_TMZalone_0TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_5TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_25TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_50TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_100TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_200TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_400TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_800TMZ_MGMT_P} tm_cell{sn_Verre_TMZalone_1000TMZ_MGMT_P} };
Verre_surv_TMZalone_MGMT_P_sim_cell={um_cell{sn_Verre_TMZalone_0TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_5TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_25TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_50TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_100TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_200TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_400TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_800TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_1000TMZ_MGMT_P}};
Verre_surv_TMZalone_MGMT_P_CyA_cell={CyAm_cell{sn_Verre_TMZalone_0TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_5TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_25TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_50TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_100TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_200TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_400TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_800TMZ_MGMT_P} um_cell{sn_Verre_TMZalone_1000TMZ_MGMT_P}};

Verre_surv_TMZalone_t_cell=[Verre_surv_TMZalone_MGMT_M_t_cell Verre_surv_TMZalone_MGMT_P_t_cell];
Verre_surv_TMZalone_sim_cell=[Verre_surv_TMZalone_MGMT_M_sim_cell Verre_surv_TMZalone_MGMT_P_sim_cell];
Verre_surv_TMZalone_CyA_cell=[Verre_surv_TMZalone_MGMT_M_CyA_cell Verre_surv_TMZalone_MGMT_P_CyA_cell];

Verre_surv_TMZalone_MGMT_M='mmmmmmmmm';
Verre_surv_TMZalone_MGMT_P='ppppppppp';
Verre_surv_TMZalone_MGMT=[Verre_surv_TMZalone_MGMT_M Verre_surv_TMZalone_MGMT_P];

TMZout0_surv_Verre=[TMZout0_surv_Verre_MGMT_M TMZout0_surv_Verre_MGMT_P];

plot_PK(Verre_surv_TMZalone_PKPDplot_fignumb,Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZalone_t_cell,Verre_surv_TMZalone_sim_cell,Verre_surv_TMZalone_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_adducts(Verre_surv_TMZalone_PKPDplot_fignumb+1,Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZalone_t_cell,Verre_surv_TMZalone_sim_cell,Verre_surv_TMZalone_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_ATRChk1Cellcycle(Verre_surv_TMZalone_PKPDplot_fignumb+2,Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZalone_t_cell,Verre_surv_TMZalone_sim_cell,Verre_surv_TMZalone_CyA_cell,Verre_surv_TMZalone_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_p53Mdm2(Verre_surv_TMZalone_PKPDplot_fignumb+3,Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZalone_t_cell,Verre_surv_TMZalone_sim_cell,Verre_surv_TMZalone_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))

%% Maité Verreault Simulations cell TMZ survival (TMZ + Nip)
Verre_surv_TMZNip_MGMT_M_t_cell={tm_cell{sn_Verre_TMZNip_0TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_5TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_25TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_50TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_100TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_200TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_400TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_800TMZ_MGMT_M} tm_cell{sn_Verre_TMZNip_1000TMZ_MGMT_M} };
Verre_surv_TMZNip_MGMT_M_sim_cell={um_cell{sn_Verre_TMZNip_0TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_5TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_25TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_50TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_100TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_200TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_400TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_800TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_1000TMZ_MGMT_M}};
Verre_surv_TMZNip_MGMT_M_CyA_cell={CyAm_cell{sn_Verre_TMZNip_0TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_5TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_25TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_50TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_100TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_200TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_400TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_800TMZ_MGMT_M} um_cell{sn_Verre_TMZNip_1000TMZ_MGMT_M}};

Verre_surv_TMZNip_MGMT_P_t_cell={tm_cell{sn_Verre_TMZNip_0TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_5TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_25TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_50TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_100TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_200TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_400TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_800TMZ_MGMT_P} tm_cell{sn_Verre_TMZNip_1000TMZ_MGMT_P} };
Verre_surv_TMZNip_MGMT_P_sim_cell={um_cell{sn_Verre_TMZNip_0TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_5TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_25TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_50TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_100TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_200TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_400TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_800TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_1000TMZ_MGMT_P}};
Verre_surv_TMZNip_MGMT_P_CyA_cell={CyAm_cell{sn_Verre_TMZNip_0TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_5TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_25TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_50TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_100TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_200TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_400TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_800TMZ_MGMT_P} um_cell{sn_Verre_TMZNip_1000TMZ_MGMT_P}};

Verre_surv_TMZNip_t_cell=[Verre_surv_TMZNip_MGMT_M_t_cell Verre_surv_TMZNip_MGMT_P_t_cell];
Verre_surv_TMZNip_sim_cell=[Verre_surv_TMZNip_MGMT_M_sim_cell Verre_surv_TMZNip_MGMT_P_sim_cell];
Verre_surv_TMZNip_CyA_cell=[Verre_surv_TMZNip_MGMT_M_CyA_cell Verre_surv_TMZNip_MGMT_P_CyA_cell];

Verre_surv_TMZNip_MGMT_M='mmmmmmmmm';
Verre_surv_TMZNip_MGMT_P='ppppppppp';
Verre_surv_TMZNip_MGMT=[Verre_surv_TMZNip_MGMT_M Verre_surv_TMZNip_MGMT_P];

TMZout0_surv_Verre=[TMZout0_surv_Verre_MGMT_M TMZout0_surv_Verre_MGMT_P];

plot_PK(Verre_surv_TMZNip_PKPDplot_fignumb,Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZNip_t_cell,Verre_surv_TMZNip_sim_cell,Verre_surv_TMZNip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_adducts(Verre_surv_TMZNip_PKPDplot_fignumb+1,Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZNip_t_cell,Verre_surv_TMZNip_sim_cell,Verre_surv_TMZNip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_ATRChk1Cellcycle(Verre_surv_TMZNip_PKPDplot_fignumb+2,Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZNip_t_cell,Verre_surv_TMZNip_sim_cell,Verre_surv_TMZNip_CyA_cell,Verre_surv_TMZNip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_p53Mdm2(Verre_surv_TMZNip_PKPDplot_fignumb+3,Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZNip_t_cell,Verre_surv_TMZNip_sim_cell,Verre_surv_TMZNip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))

%% Maité Verreault Simulations cell TMZ survival (TMZ + RI1)
Verre_surv_TMZRI1_MGMT_M_t_cell={tm_cell{sn_Verre_TMZRI1_0TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_5TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_25TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_50TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_100TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_200TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_400TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_800TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_M} };
Verre_surv_TMZRI1_MGMT_M_sim_cell={um_cell{sn_Verre_TMZRI1_0TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_5TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_25TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_50TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_100TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_200TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_400TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_800TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_M}};
Verre_surv_TMZRI1_MGMT_M_CyA_cell={CyAm_cell{sn_Verre_TMZRI1_0TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_5TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_25TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_50TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_100TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_200TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_400TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_800TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_M}};
 
Verre_surv_TMZRI1_MGMT_P_t_cell={tm_cell{sn_Verre_TMZRI1_0TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_5TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_25TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_50TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_100TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_200TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_400TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_800TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_P} };
Verre_surv_TMZRI1_MGMT_P_sim_cell={um_cell{sn_Verre_TMZRI1_0TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_5TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_25TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_50TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_100TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_200TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_400TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_800TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_P}};
Verre_surv_TMZRI1_MGMT_P_CyA_cell={CyAm_cell{sn_Verre_TMZRI1_0TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_5TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_25TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_50TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_100TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_200TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_400TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_800TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1_1000TMZ_MGMT_P}};
 
Verre_surv_TMZRI1_t_cell=[Verre_surv_TMZRI1_MGMT_M_t_cell Verre_surv_TMZRI1_MGMT_P_t_cell];
Verre_surv_TMZRI1_sim_cell=[Verre_surv_TMZRI1_MGMT_M_sim_cell Verre_surv_TMZRI1_MGMT_P_sim_cell];
Verre_surv_TMZRI1_CyA_cell=[Verre_surv_TMZRI1_MGMT_M_CyA_cell Verre_surv_TMZRI1_MGMT_P_CyA_cell];
 
Verre_surv_TMZRI1_MGMT_M='mmmmmmmmm';
Verre_surv_TMZRI1_MGMT_P='ppppppppp';
Verre_surv_TMZRI1_MGMT=[Verre_surv_TMZRI1_MGMT_M Verre_surv_TMZRI1_MGMT_P];
 
TMZout0_surv_Verre=[TMZout0_surv_Verre_MGMT_M TMZout0_surv_Verre_MGMT_P];
 
plot_PK(Verre_surv_TMZRI1_PKPDplot_fignumb,Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1_t_cell,Verre_surv_TMZRI1_sim_cell,Verre_surv_TMZRI1_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_adducts(Verre_surv_TMZRI1_PKPDplot_fignumb+1,Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1_t_cell,Verre_surv_TMZRI1_sim_cell,Verre_surv_TMZRI1_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_ATRChk1Cellcycle(Verre_surv_TMZRI1_PKPDplot_fignumb+2,Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1_t_cell,Verre_surv_TMZRI1_sim_cell,Verre_surv_TMZRI1_CyA_cell,Verre_surv_TMZRI1_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_p53Mdm2(Verre_surv_TMZRI1_PKPDplot_fignumb+3,Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1_t_cell,Verre_surv_TMZRI1_sim_cell,Verre_surv_TMZRI1_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))

%% MaitÃ© Verreault Simulations cell TMZ survival (TMZ + RI1 + Nip)
Verre_surv_TMZRI1Nip_MGMT_M_t_cell={tm_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_M} tm_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_M} };
Verre_surv_TMZRI1Nip_MGMT_M_sim_cell={um_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_M}};
Verre_surv_TMZRI1Nip_MGMT_M_CyA_cell={CyAm_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_M} um_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_M}};
 
Verre_surv_TMZRI1Nip_MGMT_P_t_cell={tm_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_P} tm_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_P} };
Verre_surv_TMZRI1Nip_MGMT_P_sim_cell={um_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_P}};
Verre_surv_TMZRI1Nip_MGMT_P_CyA_cell={CyAm_cell{sn_Verre_TMZRI1Nip_0TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_5TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_25TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_50TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_100TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_200TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_400TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_800TMZ_MGMT_P} um_cell{sn_Verre_TMZRI1Nip_1000TMZ_MGMT_P}};
 
Verre_surv_TMZRI1Nip_t_cell=[Verre_surv_TMZRI1Nip_MGMT_M_t_cell Verre_surv_TMZRI1Nip_MGMT_P_t_cell];
Verre_surv_TMZRI1Nip_sim_cell=[Verre_surv_TMZRI1Nip_MGMT_M_sim_cell Verre_surv_TMZRI1Nip_MGMT_P_sim_cell];
Verre_surv_TMZRI1Nip_CyA_cell=[Verre_surv_TMZRI1Nip_MGMT_M_CyA_cell Verre_surv_TMZRI1Nip_MGMT_P_CyA_cell];
 
Verre_surv_TMZRI1Nip_MGMT_M='mmmmmmmmm';
Verre_surv_TMZRI1Nip_MGMT_P='ppppppppp';
Verre_surv_TMZRI1Nip_MGMT=[Verre_surv_TMZRI1Nip_MGMT_M Verre_surv_TMZRI1Nip_MGMT_P];
 
TMZout0_surv_Verre=[TMZout0_surv_Verre_MGMT_M TMZout0_surv_Verre_MGMT_P];
 
plot_PK(Verre_surv_TMZRI1Nip_PKPDplot_fignumb,Verre_surv_TMZRI1Nip_PKPDplot_fig,Verre_surv_TMZRI1Nip_t_cell,Verre_surv_TMZRI1Nip_sim_cell,Verre_surv_TMZRI1Nip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_adducts(Verre_surv_TMZRI1Nip_PKPDplot_fignumb+1,Verre_surv_TMZRI1Nip_PKPDplot_fig,Verre_surv_TMZRI1Nip_t_cell,Verre_surv_TMZRI1Nip_sim_cell,Verre_surv_TMZRI1Nip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_ATRChk1Cellcycle(Verre_surv_TMZRI1Nip_PKPDplot_fignumb+2,Verre_surv_TMZRI1Nip_PKPDplot_fig,Verre_surv_TMZRI1Nip_t_cell,Verre_surv_TMZRI1Nip_sim_cell,Verre_surv_TMZRI1Nip_CyA_cell,Verre_surv_TMZRI1Nip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))
plot_PD_p53Mdm2(Verre_surv_TMZRI1Nip_PKPDplot_fignumb+3,Verre_surv_TMZRI1Nip_PKPDplot_fig,Verre_surv_TMZRI1Nip_t_cell,Verre_surv_TMZRI1Nip_sim_cell,Verre_surv_TMZRI1Nip_MGMT,TMZout0_surv_Verre,1e4,zeros(1,18))




end

