function [tm_cell,um_cell] = simulations_PKPD(...
    t_Verre_surv,...
    int_cond_mat,RNA_MGMT0,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    k_Chk1,kd_Chk1,kd_pChk1,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,kf_Mdm2,kd_Mdm2,...
    kf_MGMT_M,kf_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,...
    kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    kd_ser46_MGMT_M,kd_ser46_MGMT_P,...
    ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P...
    )


global sn_Verre_TMZalone_0TMZ_MGMT_M sn_Verre_TMZalone_5TMZ_MGMT_M sn_Verre_TMZalone_25TMZ_MGMT_M sn_Verre_TMZalone_50TMZ_MGMT_M sn_Verre_TMZalone_100TMZ_MGMT_M sn_Verre_TMZalone_200TMZ_MGMT_M sn_Verre_TMZalone_400TMZ_MGMT_M sn_Verre_TMZalone_800TMZ_MGMT_M sn_Verre_TMZalone_1000TMZ_MGMT_M...
    sn_Verre_TMZalone_0TMZ_MGMT_P sn_Verre_TMZalone_5TMZ_MGMT_P sn_Verre_TMZalone_25TMZ_MGMT_P sn_Verre_TMZalone_50TMZ_MGMT_P sn_Verre_TMZalone_100TMZ_MGMT_P sn_Verre_TMZalone_200TMZ_MGMT_P sn_Verre_TMZalone_400TMZ_MGMT_P sn_Verre_TMZalone_800TMZ_MGMT_P sn_Verre_TMZalone_1000TMZ_MGMT_P...
    sim_number

tm_cell=cell(1,sim_number);
um_cell=cell(1,sim_number);
%solver-> ode#15s ode#23tb

%% Maite Verreault Cell TMZ survival (TMZ alone)
%  MGMT-
for index=sn_Verre_TMZalone_0TMZ_MGMT_M:sn_Verre_TMZalone_1000TMZ_MGMT_M
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Verre_surv,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

% MGMT+
for index=sn_Verre_TMZalone_0TMZ_MGMT_P:sn_Verre_TMZalone_1000TMZ_MGMT_P
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Verre_surv,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

end

