function cost=cost_function_computation(param_scale,LO,UP,t_Jack,t_Jack_inhATR,t_Aas,t_He,t_Ka,t_Jack_surv,numb_comptime1,...
    TMZout0_Jack,TMZout0_Jack_inhATR,TMZout0_Aas,TMZout0_He_hd,TMZout0_He_ld,TMZout0_Ka_MGMT_M,TMZout0_Ka_MGMT_P,...
    TMZout0_surv_Jack_MGMT_M,TMZout0_surv_Jack_MGMT_P,...%simulations initial conditions
    TMZin0,MTICout0,MTICin0,AICout0,AICin0,Cat0,...
    mO60,RNA_MGMT0,GT0,SSB0,Cdc250,RNA_Mdm20,Mdm20,...
    MGMT0_U87_LN229,...
    cell_pop0,cell_pop_norm0_Jack_MGMT_M,cell_pop_norm0_He,...
    surv_mean_Jack_MGMT_M,surv_stddev_Jack_MGMT_M,MGMT_Jack_MGMT_M,Chk1_Jack_MGMT_M_time,Chk1_Jack_MGMT_M_norm,pChk1_Jack_MGMT_M_time,pChk1_Jack_MGMT_M,...data
    surv_mean_Jack_MGMT_P,surv_stddev_Jack_MGMT_P,MGMT_Jack_MGMT_P_time,MGMT_Jack_MGMT_P,Chk1_Jack_MGMT_P_time,Chk1_Jack_MGMT_P_norm,pChk1_Jack_MGMT_P_time,pChk1_Jack_MGMT_P,...
    VX_Jack2D,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_M,MGMT_Jack_inhATR_VXcon_MGMT_M,MGMT_Jack_inhATR_MGMT_M,...
    Chk1_Jack_inhATR_TMZVXcon_MGMT_M_norm,Chk1_Jack_inhATR_VXcon_MGMT_M_norm,Chk1_Jack_inhATR_MGMT_M_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_M,pChk1_Jack_inhATR_VXcon_MGMT_M,pChk1_Jack_inhATR_MGMT_M,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_P,MGMT_Jack_inhATR_VXcon_MGMT_P,MGMT_Jack_inhATR_MGMT_P,...
    Chk1_Jack_inhATR_TMZVXcon_MGMT_P_norm,Chk1_Jack_inhATR_VXcon_MGMT_P_norm,Chk1_Jack_inhATR_MGMT_P_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_P,pChk1_Jack_inhATR_VXcon_MGMT_P,pChk1_Jack_inhATR_MGMT_P,...
    pChk1_Aas_time,pChk1_Aas,cdc25c_Aas_time,cdc25c_Aas_norm,p53_Aas_time,p53_Aas,...
    DSB_He_ldTMZ_MGMT_M_72h,p53_He_ldTMZ_MGMT_M_24h,p53_He_ldTMZ_MGMT_M_72h,p53ser46_He_ldTMZ_MGMT_M_24h,p53ser46_He_ldTMZ_MGMT_M_72h,...
    apop_mean_He_ldTMZ_MGMT_M_120h,apop_stddev_He_ldTMZ_MGMT_M_120h,...
    p53_He_hdTMZ_MGMT_M_24h,p53_He_hdTMZ_MGMT_M_72h,p53ser46_He_hdTMZ_MGMT_M_24h,p53ser46_He_hdTMZ_MGMT_M_72h,...
    apop_mean_He_hdTMZ_MGMT_M_72h,apop_stddev_He_hdTMZ_MGMT_M_72h,apop_mean_He_hdTMZ_MGMT_M_96h,apop_stddev_He_hdTMZ_MGMT_M_96h,...
    apop_mean_He_hdTMZ_MGMT_M_120h,apop_stddev_He_hdTMZ_MGMT_M_120h,apop_mean_He_hdTMZ_MGMT_M_144h,apop_stddev_He_hdTMZ_MGMT_M_144h,...
    DSB_He_ldTMZ_MGMT_P_72h,apop_mean_He_ldTMZ_MGMT_P_120h,apop_stddev_He_ldTMZ_MGMT_P_120h,...
    apop_mean_He_hdTMZ_MGMT_P_72h,apop_stddev_He_hdTMZ_MGMT_P_72h,apop_mean_He_hdTMZ_MGMT_P_96h,apop_stddev_He_hdTMZ_MGMT_P_96h,...
    apop_mean_He_hdTMZ_MGMT_P_120h,apop_stddev_He_hdTMZ_MGMT_P_120h,apop_mean_He_hdTMZ_MGMT_P_144h,apop_stddev_He_hdTMZ_MGMT_P_144h,...
    O6Meg_Ka_MGMT_M_50TMZ_temp_Fig1A_time,O6Meg_Ka_MGMT_M_50TMZ_temp_Fig1A,...
    O6Meg_Ka_3h_MGMT_M,O6Meg_Ka_3h_MGMT_P,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...%simulation parameters
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    kd_MGMT,k_GT,k_MMR,k_BER,k_HR,kf_ATR_MGMT_M,kd_ATR,kf_Chk1_MGMT_M,kd_Chk1,n_cdc25,kd_cdc25,n_cc,n_add,...
    n_ATR,kd_p53,kd_p53Mdm2,n_Mdm2,K_Mdm2,kt_Mdm2,kt_Mdm2p53,n_p53,kf_Mdm2,n_p53int)

global sn_Jack_MGMT_M sn_Jack_MGMT_P...
    sn_Jack_inhATR_TMZVXcon_MGMT_M sn_Jack_inhATR_VXcon_MGMT_M sn_Jack_inhATR8VX_MGMT_M sn_Jack_inhATR40VX_MGMT_M sn_Jack_inhATR200VX_MGMT_M sn_Jack_inhATR1000VX_MGMT_M ...
    sn_Jack_inhATR_TMZVXcon_MGMT_P sn_Jack_inhATR_VXcon_MGMT_P sn_Jack_inhATR8VX_MGMT_P sn_Jack_inhATR40VX_MGMT_P sn_Jack_inhATR200VX_MGMT_P sn_Jack_inhATR1000VX_MGMT_P ...
    sn_Aas ...
    sn_He_0TMZ_MGMT_M_144h sn_He_1TMZ_MGMT_M_144h sn_He_2TMZ_MGMT_M_144h sn_He_3TMZ_MGMT_M_144h sn_He_4TMZ_MGMT_M_144h sn_He_5TMZ_MGMT_M_144h sn_He_10TMZ_MGMT_M_144h sn_He_15TMZ_MGMT_M_144h sn_He_20TMZ_MGMT_M_144h ...
    sn_He_12_5TMZ_MGMT_M_144h sn_He_25TMZ_MGMT_M_144h sn_He_50TMZ_MGMT_M_144h sn_He_75TMZ_MGMT_M_144h sn_He_100TMZ_MGMT_M_144h sn_He_125TMZ_MGMT_M_144h ...
    sn_He_0TMZ_MGMT_P_144h sn_He_1TMZ_MGMT_P_144h sn_He_2TMZ_MGMT_P_144h sn_He_3TMZ_MGMT_P_144h sn_He_4TMZ_MGMT_P_144h sn_He_5TMZ_MGMT_P_144h sn_He_10TMZ_MGMT_P_144h sn_He_15TMZ_MGMT_P_144h sn_He_20TMZ_MGMT_P_144h ...
    sn_He_12_5TMZ_MGMT_P_144h sn_He_25TMZ_MGMT_P_144h sn_He_50TMZ_MGMT_P_144h sn_He_75TMZ_MGMT_P_144h sn_He_100TMZ_MGMT_P_144h sn_He_125TMZ_MGMT_P_144h ...
    sn_Ka_20TMZ_MGMT_M sn_Ka_50TMZ_MGMT_M sn_Ka_75TMZ_MGMT_M sn_Ka_XTMZ_MGMT_M...
    sn_Ka_20TMZ_MGMT_P sn_Ka_50TMZ_MGMT_P sn_Ka_100TMZ_MGMT_P sn_Ka_XTMZ_MGMT_P...
    sn_surv_0TMZ_MGMT_M_144h sn_surv_1TMZ_MGMT_M_144h sn_surv_2TMZ_MGMT_M_144h sn_surv_4TMZ_MGMT_M_144h sn_surv_8TMZ_MGMT_M_144h sn_surv_16TMZ_MGMT_M_144h sn_surv_32TMZ_MGMT_M_144h ...
    sn_surv_64TMZ_MGMT_M_144h sn_surv_128TMZ_MGMT_M_144h sn_surv_256TMZ_MGMT_M_144h sn_surv_512TMZ_MGMT_M_144h sn_surv_1024TMZ_MGMT_M_144h sn_surv_3000TMZ_MGMT_M_144h...
    sn_surv_0TMZ_MGMT_P_144h sn_surv_1TMZ_MGMT_P_144h sn_surv_2TMZ_MGMT_P_144h sn_surv_4TMZ_MGMT_P_144h sn_surv_8TMZ_MGMT_P_144h sn_surv_16TMZ_MGMT_P_144h sn_surv_32TMZ_MGMT_P_144h...
    sn_surv_64TMZ_MGMT_P_144h sn_surv_128TMZ_MGMT_P_144h sn_surv_256TMZ_MGMT_P_144h sn_surv_512TMZ_MGMT_P_144h sn_surv_1024TMZ_MGMT_P_144h sn_surv_3000TMZ_MGMT_P_144h...
    sim_number

sim_indx();


%% Parameter Scaling to [LO,UP]
param=LO.*(UP./LO).^param_scale;

%% Under estimation parameters
i=1;

TMZout0_Ka_XTMZ=param(i);i=i+1;
MGMT_P0=param(i);i=i+1;
k_MGMT=param(i);i=i+1;
k_addO=param(i);i=i+1;
k_addN=param(i);i=i+1;
DSB_72h_fac=param(i);i=i+1;
k_DSBO=param(i);i=i+1;
k_DSBN=param(i);i=i+1;
k_CyA=param(i);i=i+1;
fVX=param(i);i=i+1;
kf_ATR_MGMT_P=param(i);i=i+1;
k_ATR=param(i);i=i+1;
K_add=param(i);i=i+1;
kd_pATR=param(i);i=i+1;
k_Chk1=param(i);i=i+1;
C_Chk1=param(i);i=i+1;
pChk1_ref12_5_24h=param(i);i=i+1;
pChk1_ref100_24h=param(i);i=i+1;
pChk1_ref100_48h=param(i);i=i+1;
kd_pChk1=param(i);i=i+1;
k_cdc25=param(i);i=i+1;
K_cdc25=param(i);i=i+1;
kf_p53=param(i);i=i+1;
k_p53=param(i);i=i+1;
K_ATR=param(i);i=i+1;
p53ser46_ref50_72h=param(i);i=i+1;
kp_ser46=param(i);i=i+1;
K_p53=param(i);i=i+1;
upAsy=param(i);i=i+1;
sness=param(i);i=i+1;
k_apop=param(i);i=i+1;
tED50=param(i);i=i+1;
cell_pop_norm0_Jack_MGMT_P=param(i);i=i+1;
k_dis=param(i);

%% Elements depending on under estimation PARAMETERS
[kf_MGMT_M,kf_MGMT_P,K_cc,DSB_72h,k_addEx,mN370,DSB0,...
    ATR0_MGMT_M,ATR0_8VX_MGMT_M,ATR0_40VX_MGMT_M,ATR0_200VX_MGMT_M,ATR0_1000VX_MGMT_M,pATR0_MGMT_M,...
    ATR0_MGMT_P,ATR0_8VX_MGMT_P,ATR0_40VX_MGMT_P,ATR0_200VX_MGMT_P,ATR0_1000VX_MGMT_P,pATR0_MGMT_P,...
    Chk10_MGMT_M,kf_Chk1_MGMT_P,Chk10_MGMT_P,...
    pChk10_MGMT_M,pChk10_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    p530_MGMT_M,p530_MGMT_P,p53_ser460_MGMT_M,p53_ser460_MGMT_P,kd_ser46_MGMT_M,kd_ser46_MGMT_P,ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P,kd_Mdm2] = param_dep_elem(...
    RNA_MGMT0,MGMT0_U87_LN229,MGMT_P0,kd_MGMT,...
    Cdc250,t0_cc,M_cc,A_cc,omega_cc,phi_cc,K_cdc25,n_cdc25,...
    DSB_72h_fac,DSB_He_ldTMZ_MGMT_M_72h,k_HR,k_DSBN,k_CyA,n_cc,...
    k_BER,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,k_ATR,n_add,K_add,kd_ATR,...
    fVX,VX_Jack2D,...
    kd_pATR,...
    kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,C_Chk1,...
    kd_pChk1,...
    k_cdc25,kd_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,Mdm20,n_Mdm2,K_Mdm2,kp_ser46,...
    kt_Mdm2,kt_Mdm2p53,n_p53,K_p53,RNA_Mdm20,kf_Mdm2);

%% New Initial Conditions
[int_cond_mat]= initial_cond_func(TMZout0_Jack,TMZout0_Jack_inhATR,TMZout0_Aas,TMZout0_He_ld,TMZout0_He_hd,TMZout0_Ka_MGMT_M,TMZout0_Ka_MGMT_P,TMZout0_Ka_XTMZ,...
    TMZout0_surv_Jack_MGMT_M,TMZout0_surv_Jack_MGMT_P,...
    TMZin0,MTICout0,MTICin0,AICout0,AICin0,Cat0,...
    mO60,GT0,SSB0,mN370,DSB0,Cdc250,RNA_Mdm20,Mdm20,...
    MGMT0_U87_LN229,MGMT_P0,...
    ATR0_MGMT_M,ATR0_8VX_MGMT_M,ATR0_40VX_MGMT_M,ATR0_200VX_MGMT_M,ATR0_1000VX_MGMT_M,...
    ATR0_MGMT_P,ATR0_8VX_MGMT_P,ATR0_40VX_MGMT_P,ATR0_200VX_MGMT_P,ATR0_1000VX_MGMT_P,...
    pATR0_MGMT_M,pATR0_MGMT_P,...
    Chk10_MGMT_M,Chk10_MGMT_P,...
    pChk10_MGMT_M,pChk10_MGMT_P,...
    p530_MGMT_M,p530_MGMT_P,...
    p53_ser460_MGMT_M,p53_ser460_MGMT_P);

%% PK-PD Model
[tm_cell,um_cell] = simulations_PKPD(...
    t_Jack,t_Jack_inhATR,t_Aas,t_He,t_Ka,t_Jack_surv,...
    int_cond_mat,RNA_MGMT0,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    k_Chk1,kd_Chk1,kd_pChk1,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,kf_Mdm2,kd_Mdm2,...
    kf_MGMT_M,kf_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,...
    kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    kd_ser46_MGMT_M,kd_ser46_MGMT_P,...
    ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P...
    );

%% Cell Cycle Model
CyAm_cell = simulations_CyA(tm_cell,um_cell,t0_cc,M_cc,A_cc,omega_cc,phi_cc,K_cdc25,n_cdc25);

%% Cell population 
[Jack_surv_curvm_MGMT_M,Jack_surv_curvm_MGMT_P,...
    He_ld_apop_curvm_MGMT_M_120h,He_hd_apop_curvm_MGMT_M_72h,He_hd_apop_curvm_MGMT_M_96h,He_hd_apop_curvm_MGMT_M_120h,He_hd_apop_curvm_MGMT_M_144h,...
    He_ld_apop_curvm_MGMT_P_120h,He_hd_apop_curvm_MGMT_P_72h,He_hd_apop_curvm_MGMT_P_96h,He_hd_apop_curvm_MGMT_P_120h,He_hd_apop_curvm_MGMT_P_144h,...
    tcellpopm_cell,cellpopm_cell]=simulations_surv_curv(tm_cell,um_cell,cell_pop0,k_apop,n_p53int,upAsy,sness,tED50,k_dis,...
    TMZout0_surv_Jack_MGMT_M,TMZout0_surv_Jack_MGMT_P,TMZout0_He_ld,TMZout0_He_hd,...
    numb_comptime1,...
    cell_pop_norm0_Jack_MGMT_M,cell_pop_norm0_Jack_MGMT_P,cell_pop_norm0_He);

%%%%%%%%%%%%Data Normalization
[MGMT_Jack_MGMT_M_norm,MGMT_Jack_MGMT_P_norm,...Normalized Data
    pChk1_Jack_MGMT_M_norm,pChk1_Jack_MGMT_P_norm,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_M_norm,MGMT_Jack_inhATR_VXcon_MGMT_M_norm,MGMT_Jack_inhATR_MGMT_M_norm,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_P_norm,MGMT_Jack_inhATR_VXcon_MGMT_P_norm,MGMT_Jack_inhATR_MGMT_P_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_M_norm,pChk1_Jack_inhATR_VXcon_MGMT_M_norm,pChk1_Jack_inhATR_MGMT_M_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_P_norm,pChk1_Jack_inhATR_VXcon_MGMT_P_norm,pChk1_Jack_inhATR_MGMT_P_norm,...
    pChk1_Aas_norm,p53_Aas_norm,...
    p53_He_hdTMZ_MGMT_M_24h_norm,p53_He_hdTMZ_MGMT_M_72h_norm,...
    p53_He_ldTMZ_MGMT_M_24h_norm,p53_He_ldTMZ_MGMT_M_72h_norm,...
    p53ser46_He_hdTMZ_MGMT_M_24h_norm,p53ser46_He_hdTMZ_MGMT_M_72h_norm,...
    p53ser46_He_ldTMZ_MGMT_M_24h_norm,p53ser46_He_ldTMZ_MGMT_M_72h_norm]=data_norm_withmod(...Parameters
    MGMT_Jack_MGMT_M,MGMT_Jack_MGMT_P,...Data
    pChk1_Jack_MGMT_M,pChk1_Jack_MGMT_P,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_M,MGMT_Jack_inhATR_VXcon_MGMT_M,MGMT_Jack_inhATR_MGMT_M,...
    MGMT_Jack_inhATR_TMZVXcon_MGMT_P,MGMT_Jack_inhATR_VXcon_MGMT_P,MGMT_Jack_inhATR_MGMT_P,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_M,pChk1_Jack_inhATR_VXcon_MGMT_M,pChk1_Jack_inhATR_MGMT_M,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_P,pChk1_Jack_inhATR_VXcon_MGMT_P,pChk1_Jack_inhATR_MGMT_P,...
    pChk1_Aas,p53_Aas,...
    p53_He_ldTMZ_MGMT_M_24h,p53_He_ldTMZ_MGMT_M_72h,...
    p53_He_hdTMZ_MGMT_M_24h,p53_He_hdTMZ_MGMT_M_72h,...
    p53ser46_He_hdTMZ_MGMT_M_24h,p53ser46_He_hdTMZ_MGMT_M_72h,...
    p53ser46_He_ldTMZ_MGMT_M_24h,p53ser46_He_ldTMZ_MGMT_M_72h,...
    MGMT_P0,p530_MGMT_M,...normalization value reference
    pChk1_ref12_5_24h,pChk1_ref100_24h,pChk1_ref100_48h,p53ser46_ref50_72h...
        );
    
%%%%%%%%%%%%Data Normalization END

%%%%%%%%%%%%Cost Function
[cost_Chk1_Jack_MGMT_M,cost_pChk1_Jack_MGMT_M,...
    cost_MGMT_Jack_MGMT_P,cost_Chk1_Jack_MGMT_P,cost_pChk1_Jack_MGMT_P,...
    cost_Chk1_Jack_inhATR_MGMT_M,cost_pChk1_Jack_inhATR_MGMT_M,...
    cost_Chk1_Jack_inhATR_MGMT_P,cost_pChk1_Jack_inhATR_MGMT_P,...
    cost_pChk1_Aas,cost_cdc25c_Aas,cost_p53_Aas,...
    cost_DSB_He_ldTMZ_MGMT_M_72h,cost_DSB_He_ldTMZ_MGMT_P_72h,...
    cost_p53_He_ldTMZ_MGMT_M_24h,cost_p53_He_ldTMZ_MGMT_M_72h,cost_p53ser46_He_ldTMZ_MGMT_M_24h,cost_p53ser46_He_ldTMZ_MGMT_M_72h,...
    cost_p53_He_hdTMZ_MGMT_M_24h,cost_p53_He_hdTMZ_MGMT_M_72h,cost_p53ser46_He_hdTMZ_MGMT_M_24h,cost_p53ser46_He_hdTMZ_MGMT_M_72h,...
    cost_O6MeG_Ka_MGMT_M_50TMZ_temp_Fig1A,cost_O6MeG_Ka_3h_MGMT_M,...
    cost_O6MeG_Ka_3h_MGMT_P,...
    cost_surv_Jack_MGMT_M,cost_surv_Jack_MGMT_P,...
    cost_apop_He_ld_MGMT_M_120h,cost_apop_He_hd_MGMT_M_72h,cost_apop_He_hd_MGMT_M_96h,cost_apop_He_hd_MGMT_M_120h,cost_apop_He_hd_MGMT_M_144h,...
    cost_apop_He_ld_MGMT_P_120h,cost_apop_He_hd_MGMT_P_72h,cost_apop_He_hd_MGMT_P_96h,cost_apop_He_hd_MGMT_P_120h,cost_apop_He_hd_MGMT_P_144h,...
    cost]=cost_function(...
    numb_comptime1,k_addEx,k_addN,dna,K_add,K_ATR,upAsy,sness,tED50,...%parameters
    pChk1_ref12_5_24h,pChk1_ref100_24h,pChk1_ref100_48h,...normalization value reference
    surv_mean_Jack_MGMT_M,surv_stddev_Jack_MGMT_M,Chk1_Jack_MGMT_M_time,Chk1_Jack_MGMT_M_norm,pChk1_Jack_MGMT_M_time,pChk1_Jack_MGMT_M_norm,...%data
    surv_mean_Jack_MGMT_P,surv_stddev_Jack_MGMT_P,MGMT_Jack_MGMT_P_time,MGMT_Jack_MGMT_P_norm,Chk1_Jack_MGMT_P_time,Chk1_Jack_MGMT_P_norm,pChk1_Jack_MGMT_P_time,pChk1_Jack_MGMT_P_norm,...
    Chk1_Jack_inhATR_TMZVXcon_MGMT_M_norm,Chk1_Jack_inhATR_VXcon_MGMT_M_norm,Chk1_Jack_inhATR_MGMT_M_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_M_norm,pChk1_Jack_inhATR_VXcon_MGMT_M_norm,pChk1_Jack_inhATR_MGMT_M_norm,...
    Chk1_Jack_inhATR_TMZVXcon_MGMT_P_norm,Chk1_Jack_inhATR_VXcon_MGMT_P_norm,Chk1_Jack_inhATR_MGMT_P_norm,...
    pChk1_Jack_inhATR_TMZVXcon_MGMT_P_norm,pChk1_Jack_inhATR_VXcon_MGMT_P_norm,pChk1_Jack_inhATR_MGMT_P_norm,...
    pChk1_Aas_time,pChk1_Aas_norm,cdc25c_Aas_time,cdc25c_Aas_norm,p53_Aas_time,p53_Aas_norm,...
    DSB_72h,DSB_He_ldTMZ_MGMT_M_72h,p53_He_ldTMZ_MGMT_M_24h_norm,p53_He_ldTMZ_MGMT_M_72h_norm,p53ser46_He_ldTMZ_MGMT_M_24h_norm,p53ser46_He_ldTMZ_MGMT_M_72h_norm,...
    apop_mean_He_ldTMZ_MGMT_M_120h,apop_stddev_He_ldTMZ_MGMT_M_120h,...
    p53_He_hdTMZ_MGMT_M_24h_norm,p53_He_hdTMZ_MGMT_M_72h_norm,p53ser46_He_hdTMZ_MGMT_M_24h_norm,p53ser46_He_hdTMZ_MGMT_M_72h_norm,...
    apop_mean_He_hdTMZ_MGMT_M_72h,apop_stddev_He_hdTMZ_MGMT_M_72h,apop_mean_He_hdTMZ_MGMT_M_96h,apop_stddev_He_hdTMZ_MGMT_M_96h,...
    apop_mean_He_hdTMZ_MGMT_M_120h,apop_stddev_He_hdTMZ_MGMT_M_120h,apop_mean_He_hdTMZ_MGMT_M_144h,apop_stddev_He_hdTMZ_MGMT_M_144h,...
    DSB_He_ldTMZ_MGMT_P_72h,apop_mean_He_ldTMZ_MGMT_P_120h,apop_stddev_He_ldTMZ_MGMT_P_120h,...
    apop_mean_He_hdTMZ_MGMT_P_72h,apop_stddev_He_hdTMZ_MGMT_P_72h,apop_mean_He_hdTMZ_MGMT_P_96h,apop_stddev_He_hdTMZ_MGMT_P_96h,...
    apop_mean_He_hdTMZ_MGMT_P_120h,apop_stddev_He_hdTMZ_MGMT_P_120h,apop_mean_He_hdTMZ_MGMT_P_144h,apop_stddev_He_hdTMZ_MGMT_P_144h,...
    O6Meg_Ka_MGMT_M_50TMZ_temp_Fig1A_time,O6Meg_Ka_MGMT_M_50TMZ_temp_Fig1A,...
    O6Meg_Ka_3h_MGMT_M,O6Meg_Ka_3h_MGMT_P,...
    tm_cell,um_cell,CyAm_cell,...%simulations
    Jack_surv_curvm_MGMT_M,Jack_surv_curvm_MGMT_P,...
    He_ld_apop_curvm_MGMT_M_120h,He_hd_apop_curvm_MGMT_M_72h,He_hd_apop_curvm_MGMT_M_96h,He_hd_apop_curvm_MGMT_M_120h,He_hd_apop_curvm_MGMT_M_144h,...
    He_ld_apop_curvm_MGMT_P_120h,He_hd_apop_curvm_MGMT_P_72h,He_hd_apop_curvm_MGMT_P_96h,He_hd_apop_curvm_MGMT_P_120h,He_hd_apop_curvm_MGMT_P_144h...
    );
end
 




