function [tm_cell,um_cell] = simulations_PKPD(...
    t_Jack,t_Jack_inhATR,t_Aas,t_He,t_Ka,t_Jack_surv,...
    int_cond_mat,RNA_MGMT0,...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    k_Chk1,kd_Chk1,kd_pChk1,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,kf_Mdm2,kd_Mdm2,...
    kf_MGMT_M,kf_MGMT_P,...
    kf_ATR_MGMT_M,kf_ATR_MGMT_P,...
    kf_Chk1_MGMT_M,kf_Chk1_MGMT_P,...
    kf_cdc25_MGMT_M,kf_cdc25_MGMT_P,...
    kd_ser46_MGMT_M,kd_ser46_MGMT_P,...
    ktd_Mdm2_MGMT_M,ktd_Mdm2_MGMT_P...
    )

global sn_Jack_MGMT_M sn_Jack_MGMT_P...
    sn_Jack_inhATR_TMZVXcon_MGMT_M sn_Jack_inhATR_VXcon_MGMT_M sn_Jack_inhATR8VX_MGMT_M sn_Jack_inhATR40VX_MGMT_M sn_Jack_inhATR200VX_MGMT_M sn_Jack_inhATR1000VX_MGMT_M ...
    sn_Jack_inhATR_TMZVXcon_MGMT_P sn_Jack_inhATR_VXcon_MGMT_P sn_Jack_inhATR8VX_MGMT_P sn_Jack_inhATR40VX_MGMT_P sn_Jack_inhATR200VX_MGMT_P sn_Jack_inhATR1000VX_MGMT_P ...
    sn_Aas ...
    sn_He_0TMZ_MGMT_M_144h sn_He_1TMZ_MGMT_M_144h sn_He_2TMZ_MGMT_M_144h sn_He_3TMZ_MGMT_M_144h sn_He_4TMZ_MGMT_M_144h sn_He_5TMZ_MGMT_M_144h sn_He_10TMZ_MGMT_M_144h sn_He_15TMZ_MGMT_M_144h sn_He_20TMZ_MGMT_M_144h ...
    sn_He_12_5TMZ_MGMT_M_144h sn_He_25TMZ_MGMT_M_144h sn_He_50TMZ_MGMT_M_144h sn_He_75TMZ_MGMT_M_144h sn_He_100TMZ_MGMT_M_144h sn_He_125TMZ_MGMT_M_144h ...
    sn_He_0TMZ_MGMT_P_144h sn_He_1TMZ_MGMT_P_144h sn_He_2TMZ_MGMT_P_144h sn_He_3TMZ_MGMT_P_144h sn_He_4TMZ_MGMT_P_144h sn_He_5TMZ_MGMT_P_144h sn_He_10TMZ_MGMT_P_144h sn_He_15TMZ_MGMT_P_144h sn_He_20TMZ_MGMT_P_144h ...
    sn_He_12_5TMZ_MGMT_P_144h sn_He_25TMZ_MGMT_P_144h sn_He_50TMZ_MGMT_P_144h sn_He_75TMZ_MGMT_P_144h sn_He_100TMZ_MGMT_P_144h sn_He_125TMZ_MGMT_P_144h ...
    sn_Ka_20TMZ_MGMT_M sn_Ka_50TMZ_MGMT_M sn_Ka_75TMZ_MGMT_M sn_Ka_XTMZ_MGMT_M...
    sn_Ka_20TMZ_MGMT_P sn_Ka_50TMZ_MGMT_P sn_Ka_100TMZ_MGMT_P sn_Ka_XTMZ_MGMT_P...
    sn_surv_0TMZ_MGMT_M_144h sn_surv_1TMZ_MGMT_M_144h sn_surv_2TMZ_MGMT_M_144h sn_surv_4TMZ_MGMT_M_144h sn_surv_8TMZ_MGMT_M_144h sn_surv_16TMZ_MGMT_M_144h sn_surv_32TMZ_MGMT_M_144h ...
    sn_surv_64TMZ_MGMT_M_144h sn_surv_128TMZ_MGMT_M_144h sn_surv_256TMZ_MGMT_M_144h sn_surv_512TMZ_MGMT_M_144h sn_surv_1024TMZ_MGMT_M_144h sn_surv_3000TMZ_MGMT_M_144h...
    sn_surv_0TMZ_MGMT_P_144h sn_surv_1TMZ_MGMT_P_144h sn_surv_2TMZ_MGMT_P_144h sn_surv_4TMZ_MGMT_P_144h sn_surv_8TMZ_MGMT_P_144h sn_surv_16TMZ_MGMT_P_144h sn_surv_32TMZ_MGMT_P_144h...
    sn_surv_64TMZ_MGMT_P_144h sn_surv_128TMZ_MGMT_P_144h sn_surv_256TMZ_MGMT_P_144h sn_surv_512TMZ_MGMT_P_144h sn_surv_1024TMZ_MGMT_P_144h sn_surv_3000TMZ_MGMT_P_144h...
    sim_number

tm_cell=cell(1,sim_number);
um_cell=cell(1,sim_number);
%solver-> ode#15s ode#23tb

%% Jackson
%%% MGMT-
[tm_cell{sn_Jack_MGMT_M},um_cell{sn_Jack_MGMT_M}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack,int_cond_mat(:,sn_Jack_MGMT_M),[],...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);

%%% MGMT+
[tm_cell{sn_Jack_MGMT_P},um_cell{sn_Jack_MGMT_P}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack,int_cond_mat(:,sn_Jack_MGMT_P),[],...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);

%% Jackson inhibited ATR
%%% MGMT-
for index=sn_Jack_inhATR_TMZVXcon_MGMT_M:sn_Jack_inhATR1000VX_MGMT_M
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack_inhATR,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

%%% MGMT+
for index=sn_Jack_inhATR_TMZVXcon_MGMT_P:sn_Jack_inhATR1000VX_MGMT_P
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack_inhATR,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

%% Aasland
[tm_cell{sn_Aas},um_cell{sn_Aas}]=ode23tb(@TMZ_PK_PD_ODE,t_Aas,int_cond_mat(:,sn_Aas),[],...
    Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
    k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
    omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
    k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
    kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
    kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);

%% He
%Low and High doses MGTM-
for index=sn_He_0TMZ_MGMT_M_144h:sn_He_125TMZ_MGMT_M_144h
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_He,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

%Low and High MGTM+
for index=sn_He_0TMZ_MGMT_P_144h:sn_He_125TMZ_MGMT_P_144h
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_He,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

%% Kaina 2021
% MGMT-
for index=sn_Ka_20TMZ_MGMT_M:sn_Ka_XTMZ_MGMT_M
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Ka,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

% MGMT+
for index=sn_Ka_20TMZ_MGMT_P:sn_Ka_XTMZ_MGMT_P
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Ka,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

%% Jack Simulations cell TMZ survival
%  MGMT-
for index=sn_surv_0TMZ_MGMT_M_144h:sn_surv_3000TMZ_MGMT_M_144h
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack_surv,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_M,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_M,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_M,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_M,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_M,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_M,kf_Mdm2,kd_Mdm2);
end

% MGMT+
for index=sn_surv_0TMZ_MGMT_P_144h:sn_surv_3000TMZ_MGMT_P_144h
    [tm_cell{index},um_cell{index}]=ode23tb(@TMZ_PK_PD_ODE,t_Jack_surv,int_cond_mat(:,index),[],...
        Vin,Vout,pT,pT2,pA,pA2,dna,kcat,kT0,lambdaT,kM0,lambdaM,pH0,...
        k_addO,kf_MGMT_P,RNA_MGMT0,kd_MGMT,k_MGMT,...
        omega_cc,t0_cc,M_cc,A_cc,phi_cc,...
        k_GT,k_MMR,k_addEx,k_addN,k_BER,k_DSBO,k_DSBN,k_HR,k_CyA,K_cc,n_cc,kf_ATR_MGMT_P,k_ATR,K_add,n_add,kd_ATR,kd_pATR,...
        kf_Chk1_MGMT_P,k_Chk1,kd_Chk1,kd_pChk1,kf_cdc25_MGMT_P,k_cdc25,kd_cdc25,K_cdc25,n_cdc25,...
        kf_p53,k_p53,n_ATR,K_ATR,kd_p53,kd_p53Mdm2,K_Mdm2,n_Mdm2,kp_ser46,kd_ser46_MGMT_P,kt_Mdm2,kt_Mdm2p53,K_p53,n_p53,ktd_Mdm2_MGMT_P,kf_Mdm2,kd_Mdm2);
end

end

