function [Verre_surv_TMZalone_PKPDplot_fig,Verre_surv_TMZNip_PKPDplot_fig,Verre_surv_TMZRI1_PKPDplot_fig,Verre_surv_TMZRI1Nip_PKPDplot_fig,...
    pop_model_TMZalone_survcurv_fig,pop_model_TMZNip_survcurv_fig,pop_model_TMZRI1_survcurv_fig,pop_model_TMZRI1Nip_survcurv_fig,...
    Verre_surv_TMZalone_survcurv_fig,Verre_surv_TMZNip_survcurv_fig,Verre_surv_TMZRI1_survcurv_fig,Verre_surv_TMZRI1Nip_survcurv_fig,...
    Verre_surv_survcurv_fig,...
    Verre_surv_TMZalone_PKPDplot_fignumb,Verre_surv_TMZNip_PKPDplot_fignumb,Verre_surv_TMZRI1_PKPDplot_fignumb,Verre_surv_TMZRI1Nip_PKPDplot_fignumb,...
    pop_model_TMZalone_survcurv_fignumb,pop_model_TMZNip_survcurv_fignumb,pop_model_TMZRI1_survcurv_fignumb,pop_model_TMZRI1Nip_survcurv_fignumb,...
    Verre_surv_TMZalone_survcurv_fignumb,Verre_surv_TMZNip_survcurv_fignumb,Verre_surv_TMZRI1_survcurv_fignumb,Verre_surv_TMZRI1Nip_survcurv_fignumb,...
    Verre_surv_survcurv_fignumb] = plot_control()


%% plot control
Verre_surv_TMZalone_PKPDplot_fig=0;
Verre_surv_TMZNip_PKPDplot_fig=0;
Verre_surv_TMZRI1_PKPDplot_fig=0;
Verre_surv_TMZRI1Nip_PKPDplot_fig=0;

pop_model_TMZalone_survcurv_fig=0;
pop_model_TMZNip_survcurv_fig=0;
pop_model_TMZRI1_survcurv_fig=0;
pop_model_TMZRI1Nip_survcurv_fig=0;

Verre_surv_TMZalone_survcurv_fig=0;
Verre_surv_TMZNip_survcurv_fig=0;
Verre_surv_TMZRI1_survcurv_fig=0;
Verre_surv_TMZRI1Nip_survcurv_fig=0;
Verre_surv_survcurv_fig=1;

%% plot figure number
Verre_surv_TMZalone_PKPDplot_fignumb=10;
Verre_surv_TMZNip_PKPDplot_fignumb=20;
Verre_surv_TMZRI1_PKPDplot_fignumb=30;
Verre_surv_TMZRI1Nip_PKPDplot_fignumb=40;

pop_model_TMZalone_survcurv_fignumb=15;
pop_model_TMZNip_survcurv_fignumb=25;
pop_model_TMZRI1_survcurv_fignumb=35;
pop_model_TMZRI1Nip_survcurv_fignumb=45;

Verre_surv_TMZalone_survcurv_fignumb=17;
Verre_surv_TMZNip_survcurv_fignumb=27;
Verre_surv_TMZRI1_survcurv_fignumb=37;
Verre_surv_TMZRI1Nip_survcurv_fignumb=47;
Verre_surv_survcurv_fignumb=55;
end

